/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.exygy.showkeyboard;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Context;
import android.view.inputmethod.InputMethodManager;


@Kroll.module(name="TiExygyShowKeyboardAndroid", id="com.exygy.showkeyboard")
public class TiExygyShowKeyboardAndroidModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TiExygyShowKeyboardAndroidModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TiExygyShowKeyboardAndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String showKeyboard()
	{
		Context context = TiApplication.getInstance().getApplicationContext();		
		InputMethodManager imm = (InputMethodManager)context.getSystemService(Context.INPUT_METHOD_SERVICE);
			imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, InputMethodManager.HIDE_IMPLICIT_ONLY);
		return "showing keyboard";				
	}
	
	// Methods
	@Kroll.method
	public String hideKeyboard()
	{
//		Context context = TiApplication.getInstance().getApplicationContext();		
//		InputMethodManager imm = (InputMethodManager)context.getSystemService(Context.INPUT_METHOD_SERVICE);
//				imm.hideSoftInputFromWindow(myEditText.getWindowToken(), 0);
				
		return "hiding keyboard - coming soon";				
	}	

}

